### PR TITLE
test: cleanup playwright tests (#4078)

### LINKED ISSUE #4078: Cleanup Playwright Tests
Refactor duplicative locators fix incorrectly labeled tests

### PR DESCRIPTION
**Pull request by mrtopsyt**
### Ticket
Closes #4078 

- Resolved a typo that led test descriptions to be incorrect for AnVIL-Catalog tab tests
- Refactored and added comments to `testFunctions.ts`
- Made the Pagination last page test use a filter to decrease runtime and flakiness
- Refactored Pagination tests to store content in `testFunctions.ts` and to remove `anvil-pagination.spec.ts`
- Refactored tab column names to be stored as objects indexed by their name instead of being arrays, and switched tab names to be stored as constants instead of being repeated in each `ColumnDescription`
- Redesigned sort and tab name tests to not depend on tab order
- Made all tests that have early exit conditions return a boolean value instead of calling `test.fail()`, which led to the incorrect result
- Added tsdocs where they were missing in `testFunctions.ts`

### CODE REVIEW

File: explorer/e2e/testFunctions.ts [hunk 1]
```diff
@@ -522,4 +580,445 @@ export async function testClearAll(
...
+  // Should start on first page, and there should be multiple pages available
+  await expect(page.getByText(PAGE_COUNT_REGEX, { exact: true })).toHaveText(
+    /Page 1 of [0-9]+/
+  );
+  await expect(
+    page.getByText(PAGE_COUNT_REGEX, { exact: true })
+  ).not.toHaveText("Page 1 of 1");
+
+  // Detect number of pages
+  const SplitStartingPageText = (
```
Comment (mrtopsyt) [inline explorer/e2e/testFunctions.ts]: Note to self: This shouldn't have the first character capitalized

**Review by MillenniumFalconMechanic — APPROVED** [review]
LGTM, thanks Jonah!

**Review by MillenniumFalconMechanic — APPROVED** [review]
LGTM, thanks Jonah!
