### PR TITLE
fix: fix seeding database for client-side data (#3798)

### LINKED ISSUE #3798: [AnVIL Catalog] Fix seeding database for client-side data

### PR DESCRIPTION
**Pull request by frano-m**
### Ticket
Closes #3798.

### Reviewers
@NoopDog.

### Changes
- Updated entities page handling of seeding the database for client-side data.

### CODE REVIEW

File: explorer/pages/[entityListType]/index.tsx [hunk 1]
```diff
@@ -42,9 +42,7 @@ const seedDatabase = async function seedDatabase( // TODO get rid of this duplic
   }
 
   const object = JSON.parse(rawData.toString());
-  const entities = entityMapper
-    ? Object.values(object).map(entityMapper)
-    : Object.values(object);
+  const entities = Object.values(object); // Client-side fetched entities are mapped prior to dispatch to explore state.
```
Comment (frano-m) [inline explorer/pages/[entityListType]/index.tsx:45]: Client-side fetched entities are mapped prior to dispatching the entities to explore state. Removing the mapping from the database to prevent mapping over entities twice!

**Review by NoopDog — APPROVED** [review]
