### PR TITLE
fix: corrected prod terra url #4469

### LINKED ISSUE #4469: LungMAP export to Terra points to a Terra dev instances instead of production
The current “Export” to Terra button in LungMAP points towards a dev instance of Terra instead of the production instance

Image

### PR DESCRIPTION
**Pull request by MillenniumFalconMechanic**
### Ticket

Closes #4469.

### Reviewers

@noop, @frano-m.

### Changes

- Added config for LM prod link to Terra.

### CODE REVIEW

File: site-config/lungmap/prod/config.ts [hunk 1]
```diff
@@ -14,6 +14,7 @@ const CATALOG = "lm8";
 
 const config: SiteConfig = {
   ...makeConfig(BROWSER_URL, PORTAL_URL, DATA_URL, GIT_HUB_REPO_URL, CATALOG),
+  exportToTerraUrl: "https://anvil.terra.bio/",
```
Comment (MillenniumFalconMechanic) [inline site-config/lungmap/prod/config.ts:17]: Copied AnVIL pattern [here](https://github.com/DataBiosphere/data-browser/blob/main/site-config/anvil-cmg/prod/config.ts#L16).

**Review by NoopDog — APPROVED** [review]
